package net.jqwik.api.arbitraries;

import java.util.*;
import java.util.function.*;

import org.apiguardian.api.*;

import net.jqwik.api.*;

import static org.apiguardian.api.API.Status.*;

/**
 * Use this superclass if you want to provide a specialized type of arbitrary.
 *
 * @param <T> The type of object to be generated by this arbitrary
 *
 * @see Arbitrary
 * @see Arbitraries
 */
@API(status = EXPERIMENTAL, since = "1.4.0")
public abstract class ArbitraryDecorator<T>  implements Cloneable, Arbitrary<T> {

	/**
	 * Implement by calling jqwik's standard DSL for building arbitraries.
	 *
	 * @return a new arbitrary instance
	 */
	abstract protected Arbitrary<T> arbitrary();

	@Override
	public RandomGenerator<T> generator(int genSize) {
		return arbitrary().generator(genSize);
	}

	@Override
	public boolean isUnique() {
		return arbitrary().isUnique();
	}

	@Override
	public Optional<ExhaustiveGenerator<T>> exhaustive(long maxNumberOfSamples) {
		return arbitrary().exhaustive(maxNumberOfSamples);
	}

	@Override
	public EdgeCases<T> edgeCases() {
		return arbitrary().edgeCases();
	}

	@Override
	public Arbitrary<T> edgeCases(Consumer<EdgeCases.Config<T>> configurator) {
		return arbitrary().edgeCases(configurator);
	}

	@Override
	public String toString() {
		return String.format("Decorated:%s", super.toString());
	}

	/**
	 * Use to clone current instance with its interface type
	 *
	 * @param <A> The special interface type of this arbitrary
	 * @return A cloned instance of this arbitrary
	 */
	protected <A extends Arbitrary<?>> A typedClone() {
		try {
			//noinspection unchecked
			return (A) this.clone();
		} catch (CloneNotSupportedException e) {
			throw new JqwikException(e.getMessage());
		}
	}

}
