package net.jqwik.api.constraints;

import java.lang.annotation.*;

/**
 * Constrain the range of a generated byte or Byte parameters.
 *
 * Applies to byte or Byte parameters which are also annotated with {@code @ForAll}.
 *
 * @see net.jqwik.api.ForAll
 * @see ShortRange
 * @see IntRange
 * @see LongRange
 * @see FloatRange
 * @see DoubleRange
 */
@Target({ ElementType.ANNOTATION_TYPE, ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface ByteRange {
	byte min() default 0;

	byte max();
}
